# Generated by Django 4.1.2 on 2023-08-24 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=20)),
                ('mgr', models.IntegerField()),
                ('hiredate', models.DateField()),
                ('sal', models.FloatField()),
                ('comm', models.FloatField()),
                ('deptno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100)),
                ('relase_year', models.IntegerField()),
                ('director_name', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='testapp.director')),
            ],
        ),
    ]
