# Generated by Django 4.1.2 on 2023-08-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_director_emp_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='relase_year',
            new_name='release_year',
        ),
    ]
